#!/usr/bin/env php
<?php

require(__DIR__ . '/init.php');

use Symfony\Component\Console\Application;
use \App\Commands\ProcessPhotosCommand;

$application = new Application();
$application->add(new ProcessPhotosCommand());
$application->run();
